services:
  move-script:
    # build: .  # 告诉 Docker 在当前目录寻找 Dockerfile 进行构建
    image: bililive_moveflv
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - C:/Users/sss/Videos/bili:/rec
      - C:/Users/sss/Videos/test:/live_archive